[telemetry]
enable = false
dev = false

[log]
level = "debug"

[connection]
default_protocol = "ssh"
default_user = "root"

[chef]
trusted_certs_dir = "trusted_certs"
cookbook_repo_paths = [
  "cookbook","cookbook/crm"
]

[updates]
enable = true
channel = "stable"

[data_collector]
url = "https://chef-automate.sloopstash.dv/data-collector/v0/"
token = "xxxxxxxxxxxxxxxxxxx"

[dev]
spinner = true
