version: '3'
services:
  app:
    image: sloopstash/chef:v1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    ports:
      - "2241-2245:22"
      - "8081-8085:80"
    volumes:
      - ./supervisor/conf/main.conf:/etc/supervisord.conf
      - ./supervisor/conf/sshd.ini:/etc/supervisord.d/sshd.ini
      - ./supervisor/conf/chef-client.ini:/etc/supervisord.d/chef-client.ini
    extra_hosts:
      - "chef-infra-server.sloopstash-dev.internal:100.3.1.0"
      - "chef-automate.sloopstash-dev.internal:100.3.1.0"
    depends_on:
      - redis
    networks:
      - chef-net
  redis:
    image: sloopstash/chef:v1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    ports:
      - "2251:22"
    volumes:
      - ./supervisor/conf/main.conf:/etc/supervisord.conf
      - ./supervisor/conf/sshd.ini:/etc/supervisord.d/sshd.ini
      - ./supervisor/conf/chef-client.ini:/etc/supervisord.d/chef-client.ini
    extra_hosts:
      - "chef-infra-server.sloopstash-dev.internal:100.3.1.0"
      - "chef-automate.sloopstash-dev.internal:100.3.1.0"
    networks:
      - chef-net
networks:
  chef-net:
    external:
      name: chef-net
