version: '3'
services:
  app:
    image: sloopstash/chef:v1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    ports:
      - "2241-2245:22"
      - "8081-8085:80"
    volumes:
      - /opt/kickstart-chef/supervisor/conf/main.conf:/etc/supervisord.conf
      - /opt/kickstart-chef/supervisor/conf/sshd.ini:/etc/supervisord.d/sshd.ini
      - /opt/kickstart-chef/supervisor/conf/chef-push-jobs-client.ini:/etc/supervisord.d/chef-push-jobs-client.ini
    extra_hosts:
      - "sloopstash-chef-infra-server:100.3.1.0"
    depends_on:
      - redis
    networks:
      - chef-net
  redis:
    image: sloopstash/chef:v1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    ports:
      - "2251:22"
    volumes:
      - /opt/kickstart-chef/supervisor/conf/main.conf:/etc/supervisord.conf
      - /opt/kickstart-chef/supervisor/conf/sshd.ini:/etc/supervisord.d/sshd.ini
      - /opt/kickstart-chef/supervisor/conf/chef-push-jobs-client.ini:/etc/supervisord.d/chef-push-jobs-client.ini
    extra_hosts:
      - "sloopstash-chef-infra-server:100.3.1.0"
    networks:
      - chef-net
networks:
  chef-net:
    external:
      name: chef-net
